### ISSUE TITLE
windbg.pykd.flare fails to install

### ISSUE THREAD

**Issue by crahan** [fireeye/flare-vm#151]
I'm trying to install a fresh copy of Flare VM on Windows 7 but it always fails when installing windbg.pykd.flare. It goes through the download counter twice (0-99% and then again after that) after which it fails with the below error messages. When I try to install using `cinst windbg.pykd.flare` it downloads and installs without any issues.

```
Upgrading the following packages:
windbg.pykd.flare
By upgrading you accept licenses for the packages.
windbg.pykd.flare is not installed. Installing...
[NuGet] Attempting to resolve dependency 'windbg.flare '.
Progress: Downloading windbg.pykd.flare 0.3.2.3... 99%                         w
indbg.pykd.flare not installed. An error occurred during installation:
 Unable to read data from the transport connection: An existing connection was f
orcibly closed by the remote host.
windbg.pykd.flare package files upgrade completed. Performing other installation
 steps.
The upgrade of windbg.pykd.flare was NOT successful.
windbg.pykd.flare not installed. An error occurred during installation:
 Unable to read data from the transport connection: An existing connection was f
orcibly closed by the remote host.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - windbg.pykd.flare (exited 1) - windbg.pykd.flare not installed. An error occu
rred during installation:
 Unable to read data from the transport connection: An existing connection was f
orcibly closed by the remote host.
Chocolatey reported an unsuccessful exit code of 1. See C:\Users\CraHan\AppData\
Local\Boxstarter\boxstarter.log for details.
+ Boxstarter finished Calling Chocolatey to install windbg.pykd.flare. This may
take several minutes to complete... 00:02:21.0152809
+ Boxstarter finished Calling Chocolatey to install windbg.pykd.flare. This may
take several minutes to complete... 00:02:21.0152809
ExitCode: 1
ExitCode: 1
ERROR: The running command stopped because the preference variable "ErrorActionP
reference" or common parameter is set to Stop: Failed to install windbg.pykd.fla
re
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of flarevm.installer.flare was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\flarevm.installer.flare\tools
\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - flarevm.installer.flare (exited -1) - Error while running 'C:\ProgramData\cho
colatey\lib\flarevm.installer.flare\tools\chocolateyinstall.ps1'.
 See log for details.
Chocolatey : Chocolatey reported an unsuccessful exit code of -1. See
C:\Users\CraHan\AppData\Local\Boxstarter\boxstarter.log for details.
At C:\ProgramData\boxstarter\BoxStarter.Chocolatey\Invoke-ChocolateyBoxstarter.
ps1:199 char:5
+     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,chocolatey
```

**Comment by crahan** [comment]
Manually running `cinst <package>` and then rerunning `.\install.ps1` appears to be the workaround for this.

**Comment by crahan** [comment]
Reopening the issue. While I'm able to use `cinst <package>` to get around the _Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host_ errors, it happens for every other package download.

**Comment by htnhan** [comment]
@crahan It is a rather strange issue. I can understand if one package is having issue, but not every other package. Can you verify and confirm your network connectivity is stable for your VM? Also, can you verify that there is no network based, or host based, security solution that may interrupt the download?

**Comment by crahan** [comment]
As a test I switched the network setup from NAT to bridged and it seems to be running more stable now. There's been only one error that interrupted the install, but I'm now rerunning install.ps1 and it seems to be going through as expected.

Quite strange. Looks like this is more likely a bug with VMware Fusion (possibly on macOS Mojave) than with any of the components that Flare VM uses (boxstarter, chocolatey, etc).

My apologies. I'll close it again! ;)

**Comment by Wesly-Zhang** [comment]
Hi, I encounter another issue about installing this package.

`2020-09-21 15:56:45,906 2716 [DEBUG] - Command ['C:\ProgramData\chocolatey\tools\7z.exe' x -aoa -bd -bb1 -o"C:\ProgramData\chocolatey\lib\windbg.pykd.flare\tools\pykd64" -y "C:\ProgramData\chocolatey\lib\windbg.pykd.flare\tools\pykd-0.3.2.2-cp27-win-amd64.zip"] exited with '0'.
2020-09-21 15:56:45,906 2716 [DEBUG] - 7z exit code: 0
2020-09-21 15:56:45,908 2716 [INFO ] - C:\ProgramData\chocolatey\lib\windbg.pykd.flare\tools\pykd64
**2020-09-21 15:56:45,938 2716 [ERROR] - ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find a part of the path.**
`
I have no idea about it. Is there a lack of settings for the path of the x64 platform in $windbgDir64?
`Get-ChocolateyUnzip -FileFullPath $zipFile32 -Destination $pluginPath32
Get-ChocolateyUnzip -FileFullPath $zipFile64 -Destination $pluginPath64

# Copy PyKD bootloaders to appropriate directories
$windbgDir = ${Env:ProgramFiles(x86)}
if (-Not ($windbgDir)) {
  $windbgDir = ${Env:ProgramFiles}
  
  $windbgDir32 = Join-Path $windbgDir 'Windows Kits\10\Debuggers\x86\winext'
  
  # Move correct plugin into the windbg directory
  Move-Item -Path "${pluginPath32}\pykd\*" -Destination $windbgDir32 -Force -ErrorAction Stop
  
  # Delete temporary zip directory
  Remove-Item -Path $pluginPath32 -Recurse
} else {
  $windbgDir32 = Join-Path $windbgDir 'Windows Kits\10\Debuggers\x86\winext'
  $windbgDir64 = Join-Path $windbgDir 'Windows Kits\10\Debuggers\x64\winext'
  `
Many thanks.
