### ISSUE TITLE
OllyDumpEx invalid hash

### ISSUE THREAD

**Issue by Raikia** [fireeye/flare-vm#207]
There is currently a checksum mismatch for OllyDumpEx:

![img](https://i.imgur.com/YMb4poX.png)

**Comment by lowpriority** [comment]
This problem caused by plugin update.

Better way is change package url definition in flare chocolatey repository.
Maybe currently point to latest version url, it should be archived one.
Archived version url offers same version even if plugin updated.

URL examples:
- Latest version url
  https://low-priority.appspot.com/ollydumpex/OllyDumpEx.zip
- Archived version url
  https://low-priority.appspot.com/ollydumpex/OllyDumpEx_v1.72.zip

I guess same issues exist in following packages.
 ollydbg.ollydumpex.flare
 ollydbg2.ollydumpex.flare
 x64dbg.ollydumpex.fireeye
 windbg.ollydumpex.flare

In addition, I DO NOT recommend directly download from "raw.githubusercontent.com".
I may change it without notice.
Downloading from "low-priority.appspot.com" is recommended.

**Comment by MalwareMechanic** [comment]
@lowpriority Thanks for the details! I have changed the URL for the offending packages to use: https://low-priority.appspot.com/ollydumpex/OllyDumpEx_v1.72.zip.
