### ISSUE TITLE
Only use the flare-vm as reverse engineering ,  will the vm be security?

### ISSUE THREAD

**Issue by cecini** [fireeye/flare-vm#321]
Just RE some binary,not malware. 
I see once install, the vm os will find some threats.
Just uninstall pmalabs.flare.
Is there any other package need uninstall?

**Comment by inevity** [comment]
Just uninstall pmalabs.flare. 
Is there any other package need uninstall?

**Comment by htnhan** [comment]
@cecini FLARE-VM is designed to include many tools and scripts that might be classified as malicious or potentially unwanted software. On top of my head, these packages may be flagged:
- `peid.flare`
- `nmap.flare`
- `lordpe.flare`

However, instead of installing FLARE-VM and then uninstall some tools that are flagged, I'd recommend you check out the documentation for custom installation: https://github.com/fireeye/flare-vm#customizing-packages. You can specify exactly what should be installed.

**Comment by cecini** [comment]
Only through the whole install process, we can find which pacakge need to be uninstalled.
Only use the windwos 10 defender, found that
*  ImpRec.fireeye
* kali_windowsbinaries.flare
* pmalabs.flare.
And found the malware VirTool:Win32/DefenderTamperingRestore which i cannot found which package have it ,just use defender to remove it .
Yes, maybe later will use custom install.
