### ISSUE TITLE
fakenet-ng.python.flare not installing on Windows 7 x64

### ISSUE THREAD

**Issue by donutonion** [fireeye/flare-vm#327]
> ERROR: Cannot bind argument to parameter 'Path' because it is null.

This error occurs while trying to install fakenet-ng.python.flare on Windows 7 x64

I've checked and the TOOL_LIST_DIR and TOOL_LIST_SHORTCUT environments have been set.

I then took a look at the chocolateyinstall.ps1 and it seems at $iconPath = Join-Path $toolsDir "fakenet.ico"

However, there isnt a $toolsDir variable declared, only $pkgToolsDir.

I tried changing the variable name and just running .\chocolatelyinstall.ps1 in \lib-bad\fakenet-ng.python.flare\tools\ but the installation still failed.

How do i fix this?

**Comment by htnhan** [comment]
@donutonion We just upgrade fakenet-ng.python package. Please install the `package-ng.python.fireeye` package instead of `package-ng.python.flare` using `cinst -y fakenet-ng.python.fireeye`. Another option is to retry the whole FLARE-VM installation. The latest version (v2.3.4.1) should automatically uses `fakenet-ng.python.fireeye`
