### ISSUE TITLE
How to Uninstall

### ISSUE THREAD

**Issue by theredmoose** [fireeye/flare-vm#93]
I accidently ran the install scripts from the website on my host OS instead of a VM.  How do I uninstall and reverse the script?

**Comment by htnhan** [comment]
Hi @theredmoose . At the moment, we do not have an uninstall script. We expect Flare VM to be used within a VM with snapshots. However, you can do the following manually to uninstall:

1. Look through flarevm_malware.ps1 to list all packages that were installed.
2. For each of them, uninstall the package using "choco uninstall --removedependencies <package_name>"
3. Uninstall boxstarter and chocolatey.
4. At the beginning of the flarevm_boxstarter, you also have to reverse a few other options set by the script (disable windows update, change some taskbar config, change some explorer options, enable Bing Search)

I think this will clean up most of the script. I hope this helps.

**Comment by theredmoose** [comment]
Thank you.

Where do I find the  flarevm_malware.ps1  and the flarevm_boxstarter script?

**Comment by htnhan** [comment]
It is better to uninstall BoxStarter after reversing all the options and uninstalling the packages .


The options and packages are listed in flarevm_malware.ps1

**Comment by doomedraven** [comment]
hahaha that is just a pack of tools what normally malware analyst needs, normally in vm to prevent infection of host, but you can use them on host on your risk(in case of analyzing malware on host)

**Comment by htnhan** [comment]
@NotSoOld You can still install FlareVM on the host machine. All packages should be there. However, Flare VM is designed to be installed in a VM. I strongly recommend against installing Flare VM on the host since the installer script makes many changes that may weaken the system's settings.

That being said, we currently developing a new version (check out the branch flare-vm-2.0) that better supports uninstallation and update. We will also have a detailed documentation on how to uninstall in case the need arise.

**Comment by NotSoOld** [comment]
> @NotSoOld You can still install FlareVM on the host machine. All packages should be there. However, Flare VM is designed to be installed in a VM. I strongly recommend against installing Flare VM on the host since the installer script makes many changes that may weaken the system's settings.
> 
> That being said, we currently developing a new version (check out the branch flare-vm-2.0) that better supports uninstallation and update. We will also have a detailed documentation on how to uninstall in case the need arise.

Thank you, now it's clear to me.

**Comment by htnhan** [comment]
Fixed in 237f87ecb516e06a47a21db00743c369119caf1f

You can now uninstall all packages using "choco uninstall flarevm.installer.flare"

**Comment by ciprianmp** [comment]
I did the same mistake, installing the full Flare VM on my Win 10 Pro OS.
I now try to uninstall it by using the Windows PowerShell (Admin) as I did with the installer.
I change path to the original c:\flare-vm-master then run "choco uninstall flarevm.installer.flare" but I get this error:
"flarevm.installer.flare is not installed. Cannot uninstall a non-existent package."
I installed the latest flare vm as of today from here and I did choco update/upgrade all packages.
It took me 14 hours of restarts and logins, as the login always went to my wrong admin account (default admin account but with a different password) instead of my actual user I was installing to (also admin) - you might want to fix that.

What do I do wrong when i try to uninstall Flare and how to revert my pc to the previous state safely?
Thank you!

**Comment by lianli4999** [comment]
> 

I've got the same problem. Somehow it is now showing up with two accounts when i've only got the one. I've uninstalled the packages but how to get back to having just the one login? I dont even know the login for the other account

Thanks

**Comment by ArkAlr** [comment]
> 

try to use this command: choco uninstall flarevm.win10.installer.fireeye
