### ISSUE TITLE
Update radare2 and Cutter

### ISSUE THREAD

**Issue by xarkes** [fireeye/flare-vm#95]
According to those links, https://www.myget.org/F/flare/api/v2/package/radare2.flare and https://www.myget.org/F/flare/api/v2/package/cutter.flare radare2 is at version 2.3.0 and Cutter 1.3.
There are newest versions available:
* radare2 2.5.0 http://radare.org/r/down.html
* Cutter 1.4 https://github.com/radareorg/cutter/releases/tag/v1.4

**Comment by xarkes** [comment]
Is there any way to ease future updates as well?

**Comment by xarkes** [comment]
You can update to radare2 2.6.9 and Cutter 1.5

**Comment by htnhan** [comment]
@xarkes 
I upgraded Cutter to 1.5
For radare2, I only upgrade the packege to 2.6.0, which is the official release on www.radare.org.

**Comment by xarkes** [comment]
Ok thanks,
Is there any way for me to push new versions or will I have to ping you each time a new release is available?

**Comment by htnhan** [comment]
Unfortunately, the current packages are kept internally due to ... legal reasons. However, I am more than happy to have community support. Here is what I think you can do to help push new releases:

1. Create the chocolatey packages for radare2 and cutter. Everyone can contribute to Chocolatey project. For more details, please follow this link: https://chocolatey.org/docs/create-packages

2. Create an issue to let us know that there is a community package available. We will update our "radare2.flare" and "cutter.flare" packages to have a dependencies on your chocolatey packages. We still need an internal package for some house keeping like creating the right shortcut at the right location.

3. Keep your radare2 and cutter package up to date with radare2 and cutter projects. 

Thank you for using and supporting the Flare VM project.
